var menu = {
    new_list:[
        {
            icon:'&#xe622;',
            title:'最近',
            markcode:'nearest'
        }
    ],
    main_list:[
        {
            icon:'&#xe642;',
            title:'全部',
            markcode:'all'
        },
        {
            icon:'&#xe613;',
            title:'文档',
            markcode:'file'
        },
        {
            icon:'&#xe60a;',
            title:'图片',
            markcode:'picture'
        },
        {
            icon:'&#xe6d1;',
            title:'视频',
            markcode:'movie'
        },
        {
            icon:'&#xe62f;',
            title:'音乐',
            markcode:'music'
        }
    ],
    tool_list:[
        {
            icon:'&#xe6bd;',
            title:'照片',
            markcode:'photo'
        },
        {
            icon:'&#xe609;',
            title:'笔记',
            markcode:'note'
        },
        {
            icon:'&#xe634;',
            title:'保险箱',
            markcode:'safebox'
        },
        {
            icon:'&#xe635;',
            title:'分享链接',
            markcode:'sharelinks'
        },
        {
            icon:'&#xe6a1;',
            title:'回收站',
            markcode:'recovery'
        }
    ]
};
var content = {
    nearest:[
        {
            title:'QQ',
            markcode:'qq',
            editTime:'2017-12-05',
            fileSize:0,
            child:[
                {
                    title:'QQ22',
                    markcode:'qq22',
                    editTime:'2017-12-05',
                    fileSize:0,
                    child:[
                        {
                            title:'QQ33',
                            markcode:'qq33',
                            editTime:'2017-12-05',
                            fileSize:0
                        }
                    ]
                },
                {
                    title:'网络公司22',
                    markcode:'internet22',
                    editTime:'2017-12-08',
                    fileSize:0
                }
            ]
        },
        {
            title:'网络公司',
            markcode:'internet',
            editTime:'2017-12-08',
            fileSize:0
        },
        {
            title:'网络制作任务',
            markcode:'maketast',
            editTime:'2017-12-08',
            fileSize:0
        },
        {
            title:'我的腾讯文件',
            markcode:'tencent',
            editTime:'2017-12-08',
            fileSize:0
        }
    ],
    all:[
        {
            title:'QQ1',
            markcode:'qq1',
            editTime:'2017-12-05',
            fileSize:0
        },
        {
            title:'网络公司1',
            markcode:'internet1',
            editTime:'2017-12-08',
            fileSize:0
        },
        {
            title:'网络制作任务1',
            markcode:'maketast1',
            editTime:'2017-12-08',
            fileSize:0
        }
    ]
};